version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "6080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build: .
    ports:
      - "6081:6080"

  app2:
    build: .
    ports:
      - "6082:6080"

  app3:
    build: .
    ports:
      - "6083:6080"